// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmfxcyexpyiebunmqybm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptZnhjeWV4cHlpZWJ1bm1xeWJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MzMxMzgsImV4cCI6MjA2MDEwOTEzOH0.wH466W63RSdXuz2rVwi86WzkAkvcqluvNOyKsMK0LgE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);